import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { z } from 'zod';
import {
  createStableStream,
  hydrate,
  type HydrateOptions,
  type StreamCompletionReason,
} from '@stable-stream/core';

export interface UseStableStreamOptions<T extends z.ZodTypeAny> {
  /** Zod schema defining the expected shape */
  schema: T;
  /** Async iterable of JSON string chunks or a static raw JSON string. Pass null/undefined to not start streaming. */
  source: AsyncIterable<string> | string | null | undefined;
  /** Hydration options (e.g., maxDepth) */
  hydrateOptions?: HydrateOptions;
  /** Throttle updates to animation frames (true), completely disable (false), or throttle by a specific millisecond delay (number) (default: true) */
  throttle?: boolean | number;
  /** Called when streaming completes */
  onComplete?: (data: z.infer<T>) => void;
  /** Called on error */
  onError?: (error: Error) => void;
  /**
   * Whether to trim unfilled skeleton array items after the stream completes.
   * If true, pre-filled array items generated by schema `.min()` that don't receive
   * actual data will be removed.
   * @default false
   */
  trim?: boolean;
}

export interface UseStableStreamResult<T> {
  /** Current data (always complete shape from schema) */
  data: T;
  /** True while actively receiving chunks */
  isStreaming: boolean;
  /** True when stream has finished successfully */
  isComplete: boolean;
  /** True when stream ended with incomplete JSON or errored before full completion */
  isPartial: boolean;
  /** Machine-readable completion status for diagnostics */
  completionReason: StreamCompletionReason | null;
  /** Error if stream failed */
  error: Error | null;
  /** Paths that changed in the last update */
  changedPaths: string[];
  /** Reset to initial skeleton state */
  reset: () => void;
}

// Combined state to reduce re-renders (single setState call)
interface StreamState<T> {
  data: T;
  isStreaming: boolean;
  isComplete: boolean;
  isPartial: boolean;
  completionReason: StreamCompletionReason | null;
  error: Error | null;
  changedPaths: string[];
}

/**
 * React hook for streaming structured JSON from LLMs.
 *
 * Performance notes:
 * - Uses single state object to batch updates (1 re-render per update)
 * - RAF throttling limits to 60fps max
 * - Structural sharing from core ensures efficient reconciliation
 * - Callbacks stored in refs to avoid effect re-runs
 *
 * @example
 * ```tsx
 * const { data, isStreaming } = useStableStream({
 *   schema: UserSchema,
 *   source: textStream,
 * });
 *
 * return (
 *   <div>
 *     <h1>{data.name || 'Loading...'}</h1>
 *     {isStreaming && <Spinner />}
 *   </div>
 * );
 * ```
 */
export function useStableStream<T extends z.ZodTypeAny>(
  options: UseStableStreamOptions<T>
): UseStableStreamResult<z.infer<T>> {
  const { schema, source, hydrateOptions, throttle = true, onComplete, onError, trim = false } = options;

  // Memoize initial skeleton to avoid recreating on every render
  const initialSkeleton = useMemo(
    () => hydrate(schema, hydrateOptions),
    [schema, hydrateOptions]
  );

  // Single state object for atomic updates (reduces re-renders)
  const [state, setState] = useState<StreamState<z.infer<T>>>(() => ({
    data: initialSkeleton,
    isStreaming: false,
    isComplete: false,
    isPartial: false,
    completionReason: null,
    error: null,
    changedPaths: [],
  }));

  // Store callbacks in refs to avoid effect dependency changes
  const onCompleteRef = useRef(onComplete);
  const onErrorRef = useRef(onError);
  onCompleteRef.current = onComplete;
  onErrorRef.current = onError;

  // Track if component is mounted
  const mountedRef = useRef(true);
  // Track pending RAF update
  const rafRef = useRef<number | null>(null);
  // Track pending timer update
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Last update timestamp for time-based throttling
  const lastUpdateRef = useRef<number>(0);
  
  // Pending data for RAF or time throttling
  const pendingUpdateRef = useRef<{
    data: z.infer<T> | null;
    isPartial: boolean;
    completionReason: StreamCompletionReason | null;
    changedPaths: Set<string>;
  } | null>(null);

  const clearPendingFrame = useCallback(() => {
    if (rafRef.current) {
      cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
    }
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
    pendingUpdateRef.current = null;
  }, []);

  const reset = useCallback(() => {
    clearPendingFrame();
    const skeleton = hydrate(schema, hydrateOptions);
    setState({
      data: skeleton,
      isStreaming: false,
      isComplete: false,
      isPartial: false,
      completionReason: null,
      error: null,
      changedPaths: [],
    });
  }, [schema, hydrateOptions, clearPendingFrame]);

  // Cleanup on unmount
  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      clearPendingFrame();
    };
  }, [clearPendingFrame]);

  // Main streaming effect
  useEffect(() => {
    // No source - don't start streaming
    if (!source) {
      return;
    }

    // Reset state for new stream (single setState = single re-render)
    const skeleton = hydrate(schema, hydrateOptions);
    setState({
      data: skeleton,
      isStreaming: true,
      isComplete: false,
      isPartial: false,
      completionReason: null,
      error: null,
      changedPaths: [],
    });

    let aborted = false;
    let actualSource = source;

    // DX Feature: Wrapper for static strings
    if (typeof source === 'string') {
      actualSource = {
        async *[Symbol.asyncIterator]() {
          const chunkSize = 15; // Simulate network chunks
          for (let i = 0; i < source.length; i += chunkSize) {
            // Small artificial delay to simulate streaming
            await new Promise(r => setTimeout(r, 10));
            yield source.slice(i, Math.min(i + chunkSize, source.length));
          }
        }
      };
    }

    const runStream = async () => {
      try {
        const stream = createStableStream({
          schema,
          source: actualSource as AsyncIterable<string>,
          hydrateOptions,
          trim,
        });

        for await (const update of stream) {
          if (aborted || !mountedRef.current) break;

          if (update.state === 'error' && update.error) {
            clearPendingFrame();
            setState(prev => ({
              ...prev,
              error: update.error!,
              isStreaming: false,
              isPartial: update.isPartial,
              completionReason: update.completionReason,
            }));
            onErrorRef.current?.(update.error);
            break;
          }

          if (update.state === 'complete') {
            const pendingPaths = pendingUpdateRef.current?.changedPaths || new Set<string>();
            for (const path of update.changedPaths) pendingPaths.add(path);
            
            const mergedPaths = Array.from(pendingPaths);

            // Final update - bypass throttle, ensure data is set
            clearPendingFrame();
            setState({
              data: update.data,
              isStreaming: false,
              isComplete: true,
              isPartial: update.isPartial,
              completionReason: update.completionReason,
              error: null,
              changedPaths: mergedPaths,
            });
            onCompleteRef.current?.(update.data);
            continue;
          }

          // Streaming update (with optional throttling)
          if (throttle !== false) {
            if (!pendingUpdateRef.current) {
              pendingUpdateRef.current = {
                data: null,
                isPartial: false,
                completionReason: null,
                changedPaths: new Set<string>(),
              };
            }
            
            pendingUpdateRef.current.data = update.data;
            pendingUpdateRef.current.isPartial = update.isPartial;
            pendingUpdateRef.current.completionReason = update.completionReason;
            for (const path of update.changedPaths) {
               pendingUpdateRef.current.changedPaths.add(path);
            }

            const flushUpdate = () => {
              const pendingUpdate = pendingUpdateRef.current;
              pendingUpdateRef.current = null;
              rafRef.current = null;
              timerRef.current = null;
              lastUpdateRef.current = Date.now();

              if (mountedRef.current && pendingUpdate?.data !== null) {
                const finalPaths = Array.from(pendingUpdate.changedPaths);
                setState(prev => ({
                  ...prev,
                  data: pendingUpdate.data,
                  isPartial: pendingUpdate.isPartial,
                  completionReason: pendingUpdate.completionReason,
                  changedPaths: finalPaths,
                }));
              }
            };

            if (throttle === true) {
               // Standard RAF frame throttling
               if (!rafRef.current) {
                 rafRef.current = requestAnimationFrame(flushUpdate);
               }
            } else if (typeof throttle === 'number') {
               // Time-based numerical throttling (e.g. throttle: 100 ensures max one update per 100ms)
               const now = Date.now();
               const timeSinceLastUpdate = now - lastUpdateRef.current;
               
               if (timeSinceLastUpdate >= throttle) {
                  // We can update immediately
                  flushUpdate();
               } else if (!timerRef.current) {
                  // Schedule for later
                  const delay = throttle - timeSinceLastUpdate;
                  timerRef.current = setTimeout(flushUpdate, delay);
               }
            }
          } else {
            // No throttling
            setState(prev => ({
              ...prev,
              data: update.data,
              isPartial: update.isPartial,
              completionReason: update.completionReason,
              changedPaths: update.changedPaths,
            }));
          }
        }
      } catch (err) {
        if (aborted || !mountedRef.current) return;

        clearPendingFrame();
        const error = err instanceof Error ? err : new Error(String(err));
        setState(prev => ({
          ...prev,
          error,
          isStreaming: false,
          isPartial: true,
          completionReason: 'source_error',
        }));
        onErrorRef.current?.(error);
      }
    };

    runStream();

    return () => {
      aborted = true;
      clearPendingFrame();
    };
  }, [source, schema, hydrateOptions, throttle, trim, clearPendingFrame]); // Note: callbacks removed from deps

  return {
    data: state.data,
    isStreaming: state.isStreaming,
    isComplete: state.isComplete,
    isPartial: state.isPartial,
    completionReason: state.completionReason,
    error: state.error,
    changedPaths: state.changedPaths,
    reset,
  };
}
