/**
 * Stream Orchestrator
 *
 * Wires together: Parser → Hydrate → Merge
 * Emits stable, type-safe data on each chunk.
 */

import { z } from "zod";
import { hydrate, type HydrateOptions } from "../hydrate";
import { createIncrementalParser, type ParserState } from "../parser";
import { applyParsedValue, trimSkeleton } from "../merge";

export type StreamState = "streaming" | "complete" | "error";
export type StreamCompletionReason =
  | "streaming"
  | "complete"
  | "incomplete_json"
  | "source_error";

export interface StreamUpdate<T> {
  /** Current merged data (always complete skeleton shape) */
  data: T;
  /** Stream state */
  state: StreamState;
  /**
   * True when stream ended without a fully closed/valid JSON object
   * or when an error interrupted the stream.
   */
  isPartial: boolean;
  /** Machine-readable completion status for diagnostics. */
  completionReason: StreamCompletionReason;
  /** Paths that changed in this update */
  changedPaths: string[];
  /** Error if state is "error" */
  error?: Error;
}

export interface StableStreamOptions<T extends z.ZodTypeAny> {
  /** Zod schema defining the expected shape */
  schema: T;
  /** Async iterable of JSON string chunks */
  source: AsyncIterable<string>;
  /** Hydration options (e.g., maxDepth) */
  hydrateOptions?: HydrateOptions;
  /** Called on each update (alternative to async iteration) */
  onUpdate?: (update: StreamUpdate<z.infer<T>>) => void;
  /**
   * Whether to trim unfilled skeleton array items after the stream completes.
   * If true, pre-filled array items generated by schema `.min()` that don't receive
   * actual data will be removed.
   * @default false
   */
  trim?: boolean;
}

/**
 * Create a stable stream that parses, hydrates, and merges JSON chunks.
 *
 * @example
 * ```ts
 * const stream = createStableStream({
 *   schema: UserSchema,
 *   source: textStream, // AsyncIterable<string> from LLM SDK
 * });
 *
 * for await (const { data, state } of stream) {
 *   console.log(data); // Always complete shape, progressively filled
 * }
 * ```
 */
export async function* createStableStream<T extends z.ZodTypeAny>(
  options: StableStreamOptions<T>
): AsyncGenerator<StreamUpdate<z.infer<T>>> {
  const { schema, source, hydrateOptions, onUpdate, trim = false } = options;

  // 1. Hydrate schema to create initial skeleton
  let data = hydrate(schema, hydrateOptions) as z.infer<T>;

  // 2. Create parser instance
  const parser = createIncrementalParser();

  // Track array lengths for trimming on completion
  const arrayLengths = new Map<string, number>();
  // Validate stream root token once we see the first non-whitespace character.
  let rootTokenValidated = false;

  try {
    // 3. Process each chunk
    for await (const chunk of source) {
      if (!rootTokenValidated) {
        const rootToken = getFirstNonWhitespaceChar(chunk);
        if (rootToken !== null) {
          assertObjectRootToken(rootToken);
          rootTokenValidated = true;
        }
      }

      const parsedValues = parser.process(chunk);

      if (parsedValues.length === 0) {
        continue; // No complete values yet
      }

      // 4. Merge each parsed value
      let anyChanged = false;
      const allChangedPaths: string[] = [];

      for (const { path, value } of parsedValues) {
        // Track array lengths from parsed indices even if value equals skeleton default.
        trackArrayLength(path, arrayLengths);

        const result = applyParsedValue(data, path, value, schema);

        if (result.changed) {
          data = result.data;
          anyChanged = true;
          allChangedPaths.push(...result.changedPaths);
        }
      }

      // 5. Emit update if changed
      if (anyChanged) {
        const update: StreamUpdate<z.infer<T>> = {
          data,
          state: "streaming",
          isPartial: false,
          completionReason: "streaming",
          changedPaths: allChangedPaths,
        };

        if (onUpdate) {
          onUpdate(update);
        }

        yield update;
      }
    }

    const parserState = parser.getState();
    const incompleteJson = isJsonIncomplete(parserState);

    // 6. Stream complete - trim unfilled skeleton items if enabled
    if (trim) {
      data = trimSkeleton(data, arrayLengths);
    }

    const finalUpdate: StreamUpdate<z.infer<T>> = {
      data,
      state: "complete",
      isPartial: incompleteJson,
      completionReason: incompleteJson ? "incomplete_json" : "complete",
      changedPaths: [],
    };

    if (onUpdate) {
      onUpdate(finalUpdate);
    }

    yield finalUpdate;
  } catch (err) {
    const error = err instanceof Error ? err : new Error(String(err));

    const errorUpdate: StreamUpdate<z.infer<T>> = {
      data,
      state: "error",
      isPartial: true,
      completionReason: "source_error",
      changedPaths: [],
      error,
    };

    if (onUpdate) {
      onUpdate(errorUpdate);
    }

    yield errorUpdate;
  }
}

function isJsonIncomplete(state: ParserState): boolean {
  return (
    state.depth > 0 ||
    state.inString ||
    state.escaped ||
    state.expectingValue ||
    state.valueStarted ||
    state.nestedDepth > 0 ||
    state.inArrayValue ||
    state.arrayItemDepth > 0 ||
    state.arrayItemBuffer.trim().length > 0
  );
}

function getFirstNonWhitespaceChar(chunk: string): string | null {
  const trimmed = chunk.trimStart();
  return trimmed.length > 0 ? trimmed[0] : null;
}

function assertObjectRootToken(token: string): void {
  if (token === "{") {
    return;
  }

  if (token === "[") {
    throw new Error(
      'Top-level JSON must be an object (e.g., {"key": value}). Root arrays are not supported.'
    );
  }

  throw new Error(
    `Top-level JSON must be an object (e.g., {"key": value}). Received "${token}" as the first JSON token.`
  );
}

/**
 * Track array lengths from parsed paths.
 * Used to trim unfilled skeleton items on completion.
 */
function trackArrayLength(path: string, lengths: Map<string, number>): void {
  // Extract array path and index from paths like "items[0]", "rows[5].name"
  const arrayMatch = path.match(/^(.+?)\[(\d+)\]/);

  if (arrayMatch) {
    const arrayPath = arrayMatch[1];
    const index = parseInt(arrayMatch[2], 10);
    const currentMax = lengths.get(arrayPath) ?? -1;

    if (index >= currentMax) {
      lengths.set(arrayPath, index + 1);
    }
  }

  // Handle nested arrays: "data.tables[0].rows[3].value" -> track "data.tables[0].rows"
  const nestedMatches = path.matchAll(/(.+?\[\d+\](?:\.[^[]+)?)\[(\d+)\]/g);
  for (const match of nestedMatches) {
    const arrayPath = match[1];
    const index = parseInt(match[2], 10);
    const currentMax = lengths.get(arrayPath) ?? -1;

    if (index >= currentMax) {
      lengths.set(arrayPath, index + 1);
    }
  }
}

/**
 * Helper to consume a stable stream and return final data.
 * Useful for simple cases where you just want the result.
 *
 * @example
 * ```ts
 * const data = await consumeStableStream({
 *   schema: UserSchema,
 *   source: textStream,
 * });
 * ```
 */
export async function consumeStableStream<T extends z.ZodTypeAny>(
  options: Omit<StableStreamOptions<T>, "onUpdate">
): Promise<z.infer<T>> {
  let finalData: z.infer<T> | undefined;

  for await (const { data, state, error } of createStableStream(options)) {
    finalData = data;

    if (state === "error" && error) {
      throw error;
    }
  }

  if (finalData === undefined) {
    throw new Error("Stream ended without data");
  }

  return finalData;
}
